### ISSUE TITLE
Server not receiving data

### ISSUE THREAD

**Issue by SergiuCip** [axibase/cadvisor#1]
Hi there,

Thank you for building such container! I found it very useful.

However, I have run the atsd01 on 10.0.0.10 and the CAdvisor and on other 3 nodes which runs docker 10.0.0.20, 10.0.0.30, 10.0.0.40 I have launched the CAdvisor replacing these params:   --atsd_storage_url=http://10.0.0.10:8088 \
  --atsd_storage_write_host=10.0.0.10:8081 \

But when you look at the Entities (Last insert) doesn't show anything. Also in the Log I get this exception message: com.axibase.tsd.web.defaultexceptionhandler

Could you please tell me what I am doing wrong?

Thanks

Regards,
Sergiu

**Comment by rodionos** [comment]
Hello,

Thank you for reporting the issue. Just to verify - you're seeing data from containers on the same docker host where atsd01 is running, and at the same time there is no data from containers on other docker hosts? Can you please check that atsd01 container is accessible (listening) on ports 8088 and 8081? 

Regards,

Sergei

**Comment by SergiuCip** [comment]
Hi Sergei,

Thank you for your fast answer. So I can see on the atsd01 the containers, however, no data comes in it is complaining about communicating between them.

However, if I run the atsd01 and CAdvisor on one host and link them together the data comes in, which also suggests that the ports are opened. What I am trying to achieve it is to have CAdvisors on my Docker hosts (having different IP addresses) so therefore, I cannot use '--link' options to link them, I have to use the IP address and the port no to connect them. However, if I use the IP address it doesn't connect. 

Moreover, if I access the IP address let's say 10.0.0.10 where my ATSD01 is, using 8088 I get Request GET method not supported.

**Comment by rodionos** [comment]
Hello, did you start cadvisor containers on docker hosts on 10.0.0.20, 10.0.0.30, 10.0.0.40 this way? Notice: there is no link. username and password should match.

sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  axibase/cadvisor:latest \
  --storage_driver=atsd \
  --storage_driver_user=user \
  --storage_driver_password=secret-pwd \
  --atsd_storage_url=http://10.0.0.10:8088 \
  --atsd_storage_write_host=10.0.0.10:8081 \
  --atsd_storage_write_protocol=tcp \
  --atsd_storage_docker_host="`hostname`" \
  --atsd_storage_property_interval=15s \
  --housekeeping_interval=15s \
  --storage_driver_buffer_duration=15s

Please login into remote cadvisor containers and check that you can connect to atsd on 10.0.0.10:

docker exec -it container_id /bin/sh
echo "debug series e:entity1 m:metric1=1" | nc 10.0.0.10 8081

If connectivity is ok, you should receive 'ok'. The echo command requires nc, so you might need to install it. Alternatively, connect with telnet of unix sock.

Regards,

Sergei

**Comment by SergiuCip** [comment]
Thanks! That does it.

On the ATSD website the params you need to pass are wrong:  --storage_driver_atsd_url:

Using the ones provided on the site doesn't work. Using the ones that you provided works.

Regards,
Sergiu
